### PR TITLE
User-defined path to graph directory

### PR DESCRIPTION
**Pull request by jafors**
Hi @AlexanderDilthey ,

as mentioned, this PR contains my solution for a user-defined graph directory.

I added a new parameter called `--customGraphDir`, which - if set - will form the full graph path together with the `--graph` parameter. 
Let's say the graph used is `PRG_MHC_GRCh38_withIMGT`, which is already build in a directory `path/to/graphs`. 
If you call HLA-LA.pl with `--graph PRG_MHC_GRCh38_withIMGT --customGraphDir path/to/graphs`, the script will use the graph from the custom directory.
If `--customGraphDir` is not set, everything will go on as it does now.

This is just a simple fix, and please mind that I'm not really fluent in Perl, so i'm happy to take directions what to change.

Thanks!
Jan

### CODE REVIEW

**Comment by AlexanderDilthey** [comment]
Hi @jafors, thank you very much for submitting this!

Question: you also modify `$additional_references_dir`. This directory contains additional reference specification files that can be pulled from GitHub, and changing this will exclude these. Is this desired?

If you have access to your own graph directory and if you want to use additional reference specification files, you could put these into `PRG_MHC_GRCh38_withIMGT/knownReferences` - would this also work?

**Comment by jafors** [comment]
You are totally correct, I don't gain anything by doing this. I'll just leave the `additional_references_dir` as it is. Moving other reference files to the `knowReferences` folder in the custom graph directory will also work.

**Comment by johanneskoester** [comment]
Hi @AlexanderDilthey any chance to merge this? As far as I understood, @jafors has done the requested change?

**Comment by AlexanderDilthey** [comment]
Hi @jafors and @johanneskoester,

Sorry, I should have merged this long ago! @jafors, thank you very much for your contribution, this is a feature other users have requested as well!

**Pull request merged**
